#!/usr/sbin/nft -f

flush ruleset

table inet filter {
	set blackhole {
		type ipv4_addr
		flags interval
		elements = { 
			14.7.0.0/16,
			176.34.0.0/16
		}
	}

	chain input {		
		type filter hook input priority filter; policy drop; 
		ip saddr @blackhole drop

		ct state vmap { invalid : drop, established : accept, related : accept }    
		iif "lo" accept
		meta l4proto { icmp, ipv6-icmp } accept		   
		
		tcp dport 22 ct state new limit rate 5/minute accept   
		ip6 saddr fe80::/64 ip6 daddr fe80::/64 udp sport 547 udp dport 546 accept		
		
		tcp dport 443 ct state new accept
	}
	chain forward {
		type filter hook forward priority filter; policy drop; 
	}
	chain output {
		type filter hook output priority filter; policy accept; 
	}
}
