#!/usr/sbin/nft -f

flush ruleset

table inet filter {
	chain input {		
		type filter hook input priority filter; policy drop; 
		iif "lo" accept
		meta l4proto { icmp, ipv6-icmp } accept
		
		ct state vmap {
		  established: accept,
		  related: accept,
		  invalid: drop
		}       
		
		tcp dport 22 ct state new limit rate 5/minute accept   
		ip6 saddr fe80::/64 ip6 daddr fe80::/64 udp sport 547 udp dport 546 accept		
		
		tcp dport 443 ct state new accept
	}
	chain forward {
		type filter hook forward priority filter;policy drop; 
	}
	chain output {
		type filter hook output priority filter;policy accept; 
	}
}